### ISSUE TITLE
GridND layout (sometimes) does not match pfft's

### ISSUE THREAD

**Issue by adematti** [rainwoodman/pmesh#48]
Hi,
Particle painting is wrong when running on *multiple* NERSC Perlmutter nodes (it is all fine on a single node, and is all fine regardless the number of nodes on Cori). This issue could be traced back to ParticleMesh's domain not matching that of pfft:
https://github.com/rainwoodman/pmesh/blob/174b3976ba112421d933f4b1b13610e5ab64eb26/pmesh/pm.py#L1446
GridND internally assumes that the 3D decomposition is ~ np.unravel_index(comm.rank, shape, order='C'):
https://github.com/rainwoodman/pmesh/blob/174b3976ba112421d933f4b1b13610e5ab64eb26/pmesh/domain.py#L387
and
https://github.com/rainwoodman/pmesh/blob/174b3976ba112421d933f4b1b13610e5ab64eb26/pmesh/domain.py#L513
but this may not be pfft's choice (causing above issues).
A dirty fix consists in passing DomainAssign to GridND:
https://github.com/adematti/pmesh/blob/d3b68787412f96c4241ea30cd35f6efddcbb3932/pmesh/pm.py#L1446

Please let me know if you want me to file a PR.
Best

**Comment by rainwoodman** [comment]
Hi!

Thanks for looking into this. I’ve been pondering how this could happen but
haven’t had a full picture as of how Permutter is different from cori in
this regard. I am slight worried this may be masking an underlying issue
regarding the platform.

Are you using different number of ranks on the two machines? Could it be
caused by the MPI used by PFFT and mpi4py have different senses of the rank
to process mapping( if an linkage issue causing them to pick up 2 different
mpi libraries)?

**Comment by adematti** [comment]
Thanks for your answer! The same number of processes gets run by the two machines.
ldd mpi4py/MPI.cpython-39-x86_64-linux-gnu.so
ldd pfft/core.cpython-39-x86_64-linux-gnu.so
show me that both point to the same MPI libs.
I should probably check how pfft decides the layout. I'm going to post it there if I find any explanation.
